name: Nix Flake Check

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a
      - run: nix flake check
